services:
  init-db:
    image: python:3.11-alpine
    container_name: db-init
    volumes:
      - ./initdb:/initdb
    working_dir: /initdb
    entrypoint: ["python", "init_db_script.py"]
    networks:
      - app-network

  database:
    image: postgres:16
    volumes:
      - db_data:/var/lib/postgresql/data
    container_name: pg-docker
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME:-jimmy}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-jimmy}
      POSTGRES_DB: ${DB_NAME:-Social-NetWork}
    ports:
      - "${DB_PORT:-5432}:5432"
    networks:
      - app-network
    depends_on:
      init-db:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-jimmy} -d ${DB_NAME:-Social-NetWork}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s

  app:
    image: socialnetwork
    container_name: spring-boot-app
    restart: always
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "${APP_PORT:-8080}:8080"
    networks:
      - app-network
    environment:
      DDL_AUTO: ${DDL_AUTO:-validate}
      SHOW_SQL: ${SHOW_SQL:-true}
      DB_HOST: ${DB_HOST:-database}
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME:-Social-NetWork}
      DB_USERNAME: ${DB_USERNAME:-jimmy}
      DB_PASSWORD: ${DB_PASSWORD:-jimmy}
      DB_DIALECT: ${DB_DIALECT:-org.hibernate.dialect.PostgreSQLDialect}

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - app-network
    depends_on:
      database:
        condition: service_healthy

volumes:
  db_data:

networks:
  app-network:
    driver: bridge