services:
  app:
    image: socialnetwork
    container_name: spring-boot-app
    restart: always
    ports:
      - "${APP_PORT:-8080}:8080"
    networks:
      - app-network
    environment:
      DDL_AUTO: ${DDL_AUTO:-validate}
      SHOW_SQL: ${SHOW_SQL:-true}
      DB_HOST: ${DB_HOST:-database}
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME:-Social-NetWork}
      DB_USERNAME: ${DB_USERNAME:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      DB_DIALECT: ${DB_DIALECT:-org.hibernate.dialect.PostgreSQLDialect}

    pgadmin:
      image: dpage/pgadmin4:latest
      container_name: pgadmin
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@admin.com}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
      ports:
        - "${PGADMIN_PORT:-5050}:80"
      networks:
        - app-network

  networks:
    app-network:
      driver: bridge